<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Logify.DataLayer\Logify.DataLayer.csproj" />
    <ProjectReference Include="..\Logify.Models\Logify.Models.csproj" />
  </ItemGroup>

</Project>
